/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Get whether the system volume is muted */
export declare function getMute(): boolean

/** Gathers the human readable device name of each output device detected */
export declare function getSoundDevices(): Array<string>

/** Gathers the current volume in percent of the default output device */
export declare function getSystemVolume(): number

/** Mute or unmute the system volume */
export declare function setMute(mute: boolean): void

/**
 * Sets the current volume in percent of the default output device.
 * The `percent` argument should be a number between 0-100.
 *
 * # On macOS
 * `cpvc` needs to mute and unmute the audio device to get the hardware device volume to sync
 */
export declare function setSystemVolume(percent: number): void
